version: '3'
services:
  zookeeper:
    image: qnib/plain-zookeeper
    ports:
      - "2181:2181"
  zkui:
    image: qnib/plain-zkui
    ports:
      - "9090:9090"
    depends_on: 
      - zookeeper
    links: 
      - zookeeper:tasks.zookeeper
  kafka:
    image: ches/kafka
    volumes:
      - kafka-data:/data
      - kafka-logs:/logs
    ports:
      - "9092:9092"
      - "7203:7203"
    depends_on: 
      - zookeeper
    environment:
      KAFKA_BROKER_ID: '1'
      ZOOKEEPER_IP: 'zookeeper'

volumes:
  kafka-data:
  kafka-logs:

networks:
  default:
    external: 
      name: kafka
